In [14]:
#1
import numpy as np
a = np.array([1, 2, 3])
var=np.linalg.matrix_rank([1,2,3])
print(var)
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5




1
<class 'numpy.ndarray'>
(3,)
1 2 3


In [ ]:
#2 b = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])
var=np.linalg.matrix_rank(b)
print(var)
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])


2
(2, 3)
1 2 4


In [17]:
#3
a= np.zeros((2,2))           # an array of all zeros
b=np.ones((1,2))             # an array of all ones
c=np.full((2,2), np.eye(2))  # a constatnt array
d=np.eye(2)                  # a 2x2 array of random numbers
e=np.random.random((2,2))    #an array filled with random values


In [18]:
#4 
a =np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b =a[:2, 1:3]
print("shape of a:",a .shape)
print("shape of b:",b.shape)
print("values in b:\n",b)

shape of a: (3, 4)
shape of b: (2, 2)
values in b:
 [[2 3]
 [6 7]]


In [52]:
#5
import numpy as np
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
b = a[:2, 1:2]
print(a[0, 1])   
b[0, 0] = 77
print(a[0, 1])  


2
77


In [20]:
#6
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2,:]
print("value or r1:",row_r1,"\nshape of r1:",row_r1.shape)
print("value or r2:",row_r2,"\nshape of r2:",row_r2.shape)
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print("value or r1:",col_r1,"\nshape of r1:",col_r1.shape)
print("value or r2:",col_r2,"\nshape of r2:",col_r2.shape)

value or r1: [5 6 7 8] 
shape of r1: (4,)
value or r2: [[5 6 7 8]] 
shape of r2: (1, 4)
value or r1: [ 2  6 10] 
shape of r1: (3,)
value or r2: [[ 2]
 [ 6]
 [10]] 
shape of r2: (3, 1)


In [22]:
#7
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


[1 4 5]
[1 4 5]


In [ ]:
#8
b = (a[0, 0],[1, 1])
c = np.array([a[0, 1],a[0, 1]])


In [30]:
#9
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b= np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
a[np.arange(4), b] +=10
print(a)


[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [33]:
#10 
a=np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print("bool_index:",bool_idx)
print("bool_index of a:",a[bool_idx])
print(a[a > 2])
print("shape:",a.shape)

bool_index: [[False False]
 [ True  True]
 [ True  True]]
bool_index of a: [3 4 5 6]
[3 4 5 6]
shape: (3, 2)


In [34]:
#11
x = np.array([1, 2])
print(x.dtype)
y = np.array([1.0, 2.0])
print(y.dtype)
z = np.array([1, 2], dtype=np.int32)
print(z.dtype)


int64
float64
int32


In [35]:
#12
x=np.array([[1,2],[3,4]],dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
 # Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))
 # Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))    
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))
# Elementwise division; both produce the array
print(x / y)    
print(np.divide(x, y))
# Elementwise square root; produces the array  
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [36]:
#13
v=np.array([9,10])
w=np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))


219
219


In [37]:
#14
x = np.array([[1,2],[3,4]])
print(x.dot(v))
print(np.dot(y, v))


[29 67]
[105. 143.]


In [ ]:
#15
y = np.array([[5,6,7],[7,8,9]])
x = np.array([[1,2],[3,4]])
print(np.sum(x))                # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))        #Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))        #Compute sum of each row, prints"[3 7]"



10
[4 6]
[3 7]
[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [41]:
#16
x = np.array([[1,2,3], [3,4,5]])
print(x)
print(x.T)

[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [ ]:
#17 
x=np.array([[1,2,3],     
            [4,5,6], 
            [7,8,9], 
            [10, 11, 12]])
v=np.array([1,0,1])
y=np.zeros(x.shape)
for i in range(x.shape[0]):
     for j in range(x.shape[1]):
         y[i,j]= x[i, j] + v[j] 
print (y)


[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [49]:
#18 
vv = np.tile(v, (4, 1))
print(vv)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [55]:
#19 
x=np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v=np.array([1,0, 1])
y= x + v #add v to each row of x using broadcasting
v=np.array([1,2,3])
w=np.array([4,5])


In [56]:
#20
x = np.array([[1,2,3], [4,5,6]])